name: example
description: The example app for tio_core.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tio_core:
    path: ../

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

flutter:
