name: tio_core
description: The core of TiO.
version: 0.0.1
homepage: https://github.com/TiO-Design/tio-core

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0

flutter:
  uses-material-design: true